### ISSUE TITLE
Error when npm run build

### ISSUE THREAD

**Issue by poiedk** [okhiroyuki/redmobile-modules-generator#3]
Error when npm run build
`(node:6321) UnhandledPromiseRejectionWarning: Error: ENOTEMPTY: directory not empty, rmdir 'node_modules'`

**Comment by okhiroyuki** [comment]
@poiedk 
Try deleting the dist folder manually, and then running the command again.

**Comment by okhiroyuki** [comment]
@poiedk 
What version of Node.js are you using?

**Comment by okhiroyuki** [comment]
@poiedk 
I have modified the code.
Please try to use the latest.

**Comment by poiedk** [comment]
> @poiedk 
> I have modified the code.
> Please try to use the latest.

Thanks, I'll try.
